### ISSUE TITLE
Change scoreboard position?

### ISSUE THREAD

**Issue by MillerSty** [MillerSty/Coen371_Assignment1#87]
![2023-08-13_20h46_09](https://github.com/MillerSty/Coen371_Assignment1/assets/99670836/b02d2137-7c7f-4765-ae1b-b62e2c7ce1ef)

I was thinking of moving scoreboards down? Not neccesarily here just to a different position, what do yall think?

**Comment by BlackSound1** [comment]
If we move them, it may be harder to see the movement of the ball, considering that it bounces on the ground now. I think they're fine as they are
